import Head from "next/head";
// import Script from "next/script";
// import Image from "next/image";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
// import styles1 from "@/styles/Home1.module.css";
// import styles2 from "@/styles/Home2.module.css";
import Dummy from "@/components/Dummy"

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export default function Home() {
    // console.log(styles);
    return (
        <>
            <Dummy />
            <style jsx>
                {`
                    .mySpan {
                        color: red;
                    }
                `}
            </style>
            <Head>
                <title>Hunting Coder</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="keywords" content="nextjs, huntingcoder blog, hunting coder" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {/* <Script src="/sc.js" strategy="lazyOnload"></Script> */}
            <div
                className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
            >
                <main className={styles.main}>
                    <nav className={styles.mainnav}>
                        <ul>
                            <Link href="/">
                                <li>Home</li>
                            </Link>
                            <Link href="/about">
                                <li>About</li>
                            </Link>
                            <Link href="/blog">
                                <li>Blog</li>
                            </Link>
                            <Link href="/contact">
                                <li>Contact Us</li>
                            </Link>
                        </ul>
                    </nav>
                    <div className={styles.intro}>
                        <h1>
                            <span className="mySpan dummy">Hunting Coder</span>
                        </h1>
                        <p>
                            A Blog For The Hunting Coders By A Hunting Coder
                        </p>
                        <h2>Popular Blogs</h2>
                        <div className="blogItem">
                            <h3>How to Learn JavaScript in 2026</h3>
                            <p>JavaScript is the language used to design logic for the web</p>
                        </div>
                        <div className="blogItem">
                            <h3>How to Learn JavaScript in 2026</h3>
                            <p>JavaScript is the language used to design logic for the web</p>
                        </div>
                        <div className="blogItem">
                            <h3>How to Learn JavaScript in 2026</h3>
                            <p>JavaScript is the language used to design logic for the web</p>
                        </div>
                        <div className="blogItem">
                            <h3>How to Learn JavaScript in 2026</h3>
                            <p>JavaScript is the language used to design logic for the web</p>
                        </div>
                    </div>
                </main>
            </div>
        </>
    );
}
