import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export default function Home() {
    return (
        <>
            <style jsx>
                {`
                    h2 {
                        font-size: 30px;
                    }
                    h3 {
                        font-size: 20px;
                    }
                `}
            </style>
            <Head>
                <title>Hunting Coder</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="keywords" content="nextjs, huntingcoder blog, hunting coder" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div
                className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
            >
                <main className={styles.main}>
                    <div className={styles.intro}>
                        <h1>
                            <span>Hunting Coder</span>
                        </h1>
                        <Image className={styles.myImg} alt="A Coder" src="/home_img.jpg" width={300} height={200} />
                        <p>
                            A Blog For The Hunting Coders By A Hunting Coder
                        </p>
                    </div>
                </main>
            </div>
        </>
    );
}
